name: Deploy Book

on:
  push:
    branches:
      - master
    paths:
      - book/**
      - .github/**
  workflow_run:
    workflows: ["Generate reading note from issue"]
    types:
      - completed

env:
  GITHUB_NAME: askming
  GITHUB_EMAIL: askming@gmail.com

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-${{ secrets.PERSONAL_READING }}-${{ hashFiles('**/requirements-jb.txt') }}
          restore-keys: |
            pip-

      - name: Install dependecies
        run: |
          pip install --upgrade pip
          pip install -r requirements-jb.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Build the book
        run: |
          jupyter-book build ./book/

      - name: Deploy htmls to gh-pages branch 
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.PERSONAL_READING }}
          publish_dir: ./book/_build/html